### PR TITLE
Changes for Swift3

### PR DESCRIPTION
**Pull request by rajeevpra**
Most of the changes are created automatically by xcode.. I had fix few issues after that. I ran all the tests successfully. Please make sure to have simulator is set to ios 9.x. It will fail on 10.x because of bug in new simulator.

### CODE REVIEW

**Comment by rajeevpra** [comment]
This failure seems to be because its trying to build with xcode7.1, this needs to be built with 8.0. Let me know if I need to update something.

**Comment by rajeevpra** [comment]
Test is failing because it is trying to run it on iOS 10 simulation and as I mentioned it will fail because of the issue #47. I need help to update config in way to make it not run on ios10. Please help.

**Comment by henrinormak** [comment]
I assume this is now actually good enough to be merged. Unfortunately, I will not be able to push the new release to cocoapods in a while, but I could still merge this. Thoughts?

**Comment by jorystiefel** [comment]
@rajeevpra I don't think it makes sense to run the tests on an outdated version of iOS, as that's not really proving that the code works. You can make these tests work in iOS 10 by creating a dummy app target with Keychain Sharing enabled, and setting the tests to run "On Host App" with that app.

**Comment by rajeevpra** [comment]
I agree @jorystiefel. I will give it a try when I get chance. It can be argued that it is still useful for people to have it as this only affects ios 10 simulator not the device.
@henrinormak I would vote merge it anyways. Let me know if can help you with release to cocoapods.

**Comment by jorystiefel** [comment]
Another note I feel worth mentioning: It seems this branch of Heimdall is not backwards compatible with the current master. We could not get our client/server to successfully talk to each other until both were on the Swift 3 branch.

**Comment by henrinormak** [comment]
I will be unavailable to discuss/test/merge this for a while as I am away from my dev machine and lack the necessary tools. Two things to note:
1. New changes must remain backwards compatible, so either there is a bug in one of them that needs fixing, or there needs to be a bump in the major version to signify non-backwards compatibility.
2. Tests must pass on the latest SDK. There might be problems with importing the system libraries, but that can be fixed, I am sure.

**Comment by henrinormak** [comment]
One last thing, based on this discussion, I am willing to give someone else merge rights to master, as well as cocoapods. This is to speed up the process of adding Swift 3 support. @jorystiefel would you be interested in this?

**Comment by jorystiefel** [comment]
@henrinormak Sure, I'd be happy to help.

**Comment by rchatham** [comment]
Definitely looking to use the swift 3 version soon! I am using it to add RSA to https://github.com/kylef/JSONWebToken.swift. Currently I'm having issues pointing the pod dependency to @rajeevpra's repository and it seems like having it is due to only being able to use official pod releases.

**Comment by henrinormak** [comment]
Added @jorystiefel as a collaborator to the repo, I would also add you to the cocoapod as an owner, but I need your email for that

**Comment by jorystiefel** [comment]
@henrinormak thank you, my email is jorystiefel at me.com

**Comment by henrinormak** [comment]
Have you registered that email with Cocoapods? It claims that you have not, if so, could tou, so that I could also add you as a contributor there

**Comment by jorystiefel** [comment]
All set.

**Comment by henrinormak** [comment]
Done on my end, I'll leave merging/testing/verifying this up to you. Once done please also push a new release to Cocoapods

**Comment by jorystiefel** [comment]
@rajeevpra @rchatham I'm going to merge this soon. I've been testing this extensively over the past week. 

The break in compatibility I noticed was due to the padding change that happened in April, not due to the Swift 3 changes. I will make updates to make the tests work on iOS 10 simulator after this is merged.

**Comment by mayooresan** [comment]
is it available in cocoapods yet?

**Comment by henrinormak** [comment]
I don't think it is, @jorystiefel could you also update the pod? You need to update the podfile withnew version number, but that's pretty much it.

**Comment by jorystiefel** [comment]
Yes, coming today.

**Comment by hools** [comment]
thanks for doing this! much appreciated =) 
can you post when the pod is updated?

**Comment by rchatham** [comment]
Please `pod trunk push`! Thank you!!

**Comment by jorystiefel** [comment]
@rchatham I'm having problems with CocoaPods crashing, sorry

**Comment by rchatham** [comment]
What's wrong? Have you tried running pod lint?

**Comment by jorystiefel** [comment]
@rchatham @hools the lint error I'm getting is:

`error: no such module 'CommonCrypto'`

Any ideas?

**Comment by rchatham** [comment]
From what I can find you will need to add a script like the one below,

[https://github.com/iosdevzone/IDZSwiftCommonCrypto/blob/master/GenerateCommonCryptoModule.swift](url)

And run it in the .podspec.

[https://github.com/iosdevzone/IDZSwiftCommonCrypto/blob/master/IDZSwiftCommonCrypto.podspec](url)

It gets mentioned it in the beginning of the realm talk here [https://realm.io/news/danny-keogan-swift-cryptography/](url).

**Comment by duyleekun** [comment]
@rchatham I followed your guidance, it fixed the CommonCrypto issue

https://github.com/henrinormak/Heimdall/compare/master...dworkvn:fix/missing-common-ctypto

**Comment by adrianbrink** [comment]
@jorystiefel The build from cocoapods is broken. Have you merged the PR?

**Pull request merged**
